hugoblox:
  schema: "2.0"
  identity:
    name: Stefano Dolci
    type: person
    tagline: Astrophysics master student
    description: |
      I'm Stefano dolci, an Astrophysics master student at the University of ____.
    organization: University of Milano-Bicocca
  theme:
    mode: system
    pack: dracula
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: serif
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
